#include "GroovePresets.h"

namespace tonwerkgroove
{
namespace
{
// Menu indices, named so the kits below read as what they are.
constexpr float triplets = 2, thirtySeconds = 3;
// The delay's note values (Tonwerk's list).
constexpr float delayQuarter = 7, delayDottedEighth = 9, delayEighth = 10, delaySixteenth = 13;

// An empty track, for readability.
constexpr const char* none = "";
} // namespace

// The tracks of each pattern in grid order: kick, snare, clap, low tom, high tom, closed hat, open hat, cymbal.
// `x` plays a step, `X` plays it accented; spaces group the beats.
const std::vector<FactoryKit>& factoryKits()
{
    static const std::vector<FactoryKit> kits {
        { "Init", "", {},
          { { "x... x... x... x...", ".... x... .... x...", none, none, none, "x.x. x.x. x.x. x.x.", none, none } } },

        // House: four on the floor, the clap on two and four, an open hat on every offbeat.
        { "Deep House", "House",
          { { "master", -1 }, { "kickTune", -2 }, { "kickDecay", 450 }, { "kickTone", 0.35f }, { "kickCharacter", 0.2f },
            { "clapDecay", 450 }, { "clapReverb", 0.45f }, { "hatClosedDecay", 35 }, { "hatClosedCharacter", 0.6f },
            { "hatClosedLevel", -4 }, { "hatOpenDecay", 280 }, { "hatOpenLevel", -3 }, { "swing", 0.56f },
            { "fxReverbDecay", 2200 } },
          { { "x... x... x... x...", none, ".... x... .... x...", none, none, "xX.x xX.x xX.x xX.x",
              "..x. ..x. ..x. ..x.", none },
            { "x... x... x... x...", none, ".... x... .... x..x", none, ".... .... .... x.x.", "xX.x xX.x xX.x xX..",
              "..x. ..x. ..x. ....", "x... .... .... ...." } } },
        { "Disco House", "House",
          { { "kickDecay", 380 }, { "kickTone", 0.5f }, { "snareTone", 0.65f }, { "snareLevel", -3 },
            { "clapLevel", -2 }, { "hatOpenDecay", 350 }, { "hatOpenTone", 0.6f }, { "tomLowTune", 0 },
            { "swing", 0.54f } },
          { { "x... x... x... x...", ".... x... .... x...", ".... x... .... x...", none, none, "x... x... x... x...",
              "..X. ..X. ..X. ..X.", none },
            { "x... x... x... x...", ".... x... .... x.xx", ".... x... .... x...", ".... .... .... ..x.",
              ".... .... .... x...", "x... x... x... x...", "..X. ..X. ..X. ....", "x... .... .... ...." } } },
        { "Garage", "House",
          { { "master", 1 }, { "kickDecay", 320 }, { "kickTone", 0.45f }, { "snareDecay", 220 }, { "snareCharacter", 0.65f },
            { "clapReverb", 0.3f }, { "hatClosedDecay", 45 }, { "hatOpenDecay", 200 }, { "swing", 0.62f } },
          { { "x... .... ..x. ....", ".... x... .... x...", ".... x... .... x...", none, none, "x.xx x.x. x.xx x...",
              none, none },
            { "x... ...x ..x. ....", ".... x... .... x..x", ".... x... .... x...", none, none, "x.xx x.x. x.xx x...",
              ".... .... .... ..x.", none } } },

        // Techno: a long driven kick, rolling hats and a rumble underneath.
        { "Berlin Techno", "Techno",
          { { "master", -3 }, { "kickTune", -3 }, { "kickDecay", 900 }, { "kickTone", 0.55f }, { "kickCharacter", 0.6f },
            { "clapLevel", -5 }, { "clapReverb", 0.55f }, { "tomLowTune", -10 }, { "tomLowDecay", 700 },
            { "tomLowTone", 0.1f }, { "tomLowCharacter", 0.0f }, { "tomLowLevel", -8 }, { "tomLowReverb", 0.6f },
            { "tomLowPan", 0 }, { "hatClosedLevel", -4 }, { "drive", 0.3f }, { "fxReverbDecay", 3200 } },
          { { "x... x... x... x...", none, ".... x... .... x...", none, none, "xX.x xX.x xX.x xX.x",
              "..x. ..x. ..x. ..x.", none },
            { "x... x... x... x...", none, ".... x... .... x...", ".xx. .xx. .xx. .xx.", none, "xX.x xX.x xX.x xX.x",
              "..x. ..x. ..x. ..x.", "x... .... .... ...." } } },
        { "Industrial", "Techno",
          { { "master", -5 }, { "kickTune", -5 }, { "kickDecay", 600 }, { "kickTone", 0.7f }, { "kickCharacter", 1.0f },
            { "snareTune", -5 }, { "snareCharacter", 0.95f }, { "snareTone", 0.2f }, { "snareDelay", 0.35f },
            { "clapCharacter", 1.0f }, { "hatClosedCharacter", 0.05f }, { "hatClosedTune", -7 },
            { "cymbalTune", -12 }, { "cymbalCharacter", 0.1f }, { "drive", 0.75f }, { "fxDelayDivision", delaySixteenth },
            { "fxDelayFeedback", 0.5f } },
          { { "x..x ..x. x... ..x.", ".... x... .... x...", ".... .... .... ...x", none, none, "x.x. x.x. x.x. x.xx",
              none, "x... .... .... ...." },
            { "x..x ..x. x..x ..x.", ".... x..x .... x...", ".... .... .x.. ...x", none, none, "xxxx x.x. xxxx x.xx",
              none, "x... .... x... ...." } } },
        { "Minimal", "Techno",
          { { "master", 5 }, { "kickDecay", 260 }, { "kickTone", 0.3f }, { "kickCharacter", 0.15f }, { "tomHighTune", 14 },
            { "tomHighDecay", 70 }, { "tomHighTone", 0.1f }, { "tomHighCharacter", 0.6f }, { "tomHighDelay", 0.4f },
            { "tomHighLevel", -6 }, { "hatClosedDecay", 22 }, { "hatClosedLevel", -3 }, { "clapDecay", 180 },
            { "clapLevel", -6 }, { "fxDelayDivision", delayDottedEighth }, { "swing", 0.55f } },
          { { "x... x... x... x...", none, ".... .... .... x...", none, "...x .... ..x. ....", "..x. ..x. ..x. ..x.",
              none, none },
            { "x... x... x... x...", none, ".... x... .... x...", none, "...x ..x. ..x. .x..", "..x. ..xx ..x. ..x.",
              none, none } } },

        // Hip-hop: a swung kick, a fat snare on two and four.
        { "Boom Bap", "Hip-Hop",
          { { "master", -1 }, { "kickTune", -1 }, { "kickDecay", 600 }, { "kickTone", 0.3f }, { "kickCharacter", 0.45f },
            { "snareTune", -3 }, { "snareDecay", 320 }, { "snareTone", 0.3f }, { "snareCharacter", 0.6f },
            { "snareReverb", 0.15f }, { "hatClosedTone", 0.35f }, { "hatClosedLevel", -3 }, { "drive", 0.25f },
            { "swing", 0.58f } },
          { { "x... ...x ..x. ....", ".... x... .... x...", none, none, none, "x.x. x.x. x.x. x.x.", none, none },
            { "x... ...x ..x. ..x.", ".... x... .... x..x", none, none, none, "x.x. x.x. x.x. x.xx",
              ".... .... .... ..x.", none } } },
        { "Lo-Fi", "Hip-Hop",
          { { "master", 1 }, { "kickTune", -3 }, { "kickDecay", 500 }, { "kickTone", 0.2f }, { "kickCharacter", 0.3f },
            { "snareTune", -4 }, { "snareTone", 0.1f }, { "snareDecay", 260 }, { "snareCharacter", 0.45f },
            { "hatClosedTone", 0.0f }, { "hatClosedCharacter", 0.7f }, { "hatClosedDecay", 50 },
            { "hatClosedLevel", -2 }, { "cymbalTone", 0.0f }, { "cymbalLevel", -10 }, { "drive", 0.55f },
            { "swing", 0.6f }, { "fxReverbDecay", 1200 } },
          { { "x... ..x. .x.. ....", ".... x... .... x...", none, none, none, "x.xx x.x. x.xx x.x.", none, none },
            { "x... ..x. .x.. ..x.", ".... x... .... x..x", none, none, none, "x.xx x.x. x.xx x.xx", none,
              "x... .... .... ...." } } },

        // Trap: thirty-second steps for the hat rolls, a long 808 bass drum.
        { "Trap", "Trap",
          { { "master", -3 }, { "rate", thirtySeconds }, { "length", 32 }, { "kickTune", -5 }, { "kickDecay", 2500 }, { "kickTone", 0.15f },
            { "kickCharacter", 0.45f }, { "snareTone", 0.7f }, { "snareCharacter", 0.7f }, { "clapReverb", 0.4f },
            { "hatClosedDecay", 40 }, { "hatClosedTone", 0.7f }, { "hatClosedLevel", -4 }, { "drive", 0.2f } },
          { { "x....... ......x. ........ ..x.....", "........ ........ x....... ........",
              "........ ........ x....... ........", none, none, "x...x... x...x... x...x.x. xxxxx...",
              none, none },
            { "x....... ......x. ........ x.x.....", "........ ........ x....... ......x.",
              "........ ........ x....... ........", none, none, "x...x... x.x.x.x. x...x... xxxxxxxx",
              "........ ........ ........ ......x.", none } } },
        { "Drill", "Trap",
          { { "master", -2 }, { "rate", thirtySeconds }, { "length", 32 }, { "kickTune", -7 }, { "kickDecay", 3000 }, { "kickTone", 0.25f },
            { "kickCharacter", 0.55f }, { "snareTune", 2 }, { "snareTone", 0.8f }, { "snareCharacter", 0.75f },
            { "snareReverb", 0.3f }, { "hatClosedDecay", 30 }, { "hatClosedTone", 0.8f }, { "hatClosedLevel", -5 },
            { "drive", 0.3f } },
          { { "x....... ........ ....x... ........", "........ ........ x....... ....x...", none, none, none,
              "x..x..x. x..x..x. x..x..x. x.x.x.x.", none, none },
            { "x....... ...x.... ....x... ........", "........ ........ x....... ....x.x.", none, none, none,
              "x..x..x. x..x..x. xxxx..x. x.xxxxxx", none, none } } },

        // Electro: a zapping kick, snappy snares and handclaps.
        { "Electro Funk", "Electro",
          { { "master", -2 }, { "kickDecay", 400 }, { "kickTone", 0.75f }, { "kickCharacter", 0.4f }, { "snareCharacter", 0.75f },
            { "snareTone", 0.7f }, { "tomHighTune", 12 }, { "tomHighDecay", 160 }, { "tomHighTone", 0.0f },
            { "tomHighCharacter", 0.0f }, { "tomHighLevel", -8 }, { "tomHighDelay", 0.3f },
            { "fxDelayDivision", delayEighth }, { "swing", 0.53f } },
          { { "x..x ..x. x... ..x.", ".... x... .... x...", ".... x... .... x...", none, ".... ..x. .x.. ....",
              "x.xx x.xx x.xx x.xx", none, none },
            { "x..x ..x. x..x ..x.", ".... x... .... x.x.", ".... x... .... x...", ".... .... .... ..xx",
              ".... ..x. .x.. xx..", "x.xx x.xx x.xx x...", none, none } } },
        { "Synthwave", "Electro",
          { { "master", -3 }, { "kickDecay", 500 }, { "kickTone", 0.4f }, { "snareDecay", 450 }, { "snareTone", 0.5f },
            { "snareReverb", 0.75f }, { "snareLevel", -2 }, { "clapReverb", 0.7f }, { "clapLevel", -6 },
            { "tomLowDecay", 650 }, { "tomLowReverb", 0.5f }, { "tomHighDecay", 550 }, { "tomHighReverb", 0.5f },
            { "hatClosedLevel", -4 }, { "fxReverbDecay", 3800 } },
          { { "x... .... x... ....", ".... x... .... x...", ".... x... .... x...", none, none, "x.x. x.x. x.x. x.x.",
              none, none },
            { "x... .... x... ....", ".... x... .... ....", ".... x... .... ....", ".... .... .... .xxx",
              ".... .... xxx. ....", "x.x. x.x. .... ....", none, "x... .... .... ...." } } },
        { "Miami Bass", "Electro",
          { { "master", -1 }, { "kickTune", -6 }, { "kickDecay", 1800 }, { "kickTone", 0.3f }, { "kickCharacter", 0.35f },
            { "snareCharacter", 0.6f }, { "clapReverb", 0.25f }, { "hatClosedLevel", -4 }, { "swing", 0.55f } },
          { { "x... ...x ..x. ....", ".... x... .... x...", ".... x... .... x...", none, none, "x.x. x.x. x.x. x.x.",
              none, none },
            { "x... ...x ..x. ..x.", ".... x... .... x...", ".... x... .... x..x", none, none, "x.x. x.x. x.xx x.xx",
              none, none } } },

        // Breaks: ghost notes between the backbeats; plain steps sound softer than accents.
        { "Breakbeat", "Breaks",
          { { "master", -1 }, { "kickDecay", 420 }, { "kickTone", 0.45f }, { "kickCharacter", 0.4f }, { "snareDecay", 280 },
            { "snareCharacter", 0.6f }, { "hatClosedLevel", -3 }, { "accent", 0.8f }, { "swing", 0.54f },
            { "drive", 0.2f } },
          { { "X... ..x. ..X. ....", ".... X..x .x.. X...", none, none, none, "x.x. x.x. x.x. x.x.", none, none },
            { "X... ..x. ..X. ..x.", ".... X..x .x.. X.xx", none, none, none, "x.x. x.x. x.x. x...",
              ".... .... .... ..x.", "x... .... .... ...." } } },
        { "Drum & Bass", "Breaks",
          { { "kickDecay", 300 }, { "kickTone", 0.55f }, { "kickCharacter", 0.35f }, { "snareTune", 3 },
            { "snareTone", 0.85f }, { "snareCharacter", 0.7f }, { "snareReverb", 0.2f }, { "hatClosedTone", 0.65f },
            { "hatClosedLevel", -4 }, { "cymbalLevel", -6 } },
          { { "x... .... ..x. ....", ".... X... .... X...", none, none, none, "x.x. x.x. x.x. x.x.", none, none },
            { "x... .... ..x. ...x", ".... X..x .... X.x.", none, none, none, "x.xx x.x. x.xx x.x.", none,
              "x... .... .... ...." } } },
        { "Jungle", "Breaks",
          { { "master", -2 }, { "kickTune", -2 }, { "kickDecay", 700 }, { "kickTone", 0.3f }, { "snareTune", 2 }, { "snareTone", 0.6f },
            { "snareCharacter", 0.55f }, { "tomLowTune", -3 }, { "tomHighTune", 2 }, { "hatClosedLevel", -4 },
            { "hatOpenLevel", -4 }, { "accent", 0.85f }, { "swing", 0.52f } },
          { { "X... ..x. ..X. ....", ".... X..x .xx. X..x", none, none, none, "x.x. x.x. x.x. x.x.",
              ".... .... .... ..x.", none },
            { "X... ..x. ..X. ...x", ".... X..x .x.x X.xx", none, ".... .... .... ..x.", ".... .... .... x...",
              "x.x. x.x. x.x. x...", none, "x... .... .... ...." } } },

        // Dubstep: half time, the snare on beat three, heavy and driven.
        { "Halftime", "Dubstep",
          { { "master", -6 }, { "kickTune", -4 }, { "kickDecay", 800 }, { "kickTone", 0.45f }, { "kickCharacter", 0.6f },
            { "snareDecay", 380 }, { "snareCharacter", 0.65f }, { "snareReverb", 0.45f }, { "clapReverb", 0.5f },
            { "hatClosedLevel", -4 }, { "drive", 0.4f }, { "fxReverbDecay", 2500 } },
          { { "x... .... .... ....", ".... .... X... ....", ".... .... X... ....", none, none,
              "x.x. x.x. x.x. x.x.", none, none },
            { "x... .... ..x. ....", ".... .... X... ..x.", ".... .... X... ....", none, none,
              "x.x. x.x. x.x. xxxx", none, "x... .... .... ...." } } },
        { "Riddim", "Dubstep",
          { { "master", -6 }, { "kickTune", -6 }, { "kickDecay", 600 }, { "kickTone", 0.6f }, { "kickCharacter", 0.8f },
            { "snareTune", -2 }, { "snareDecay", 300 }, { "snareCharacter", 0.8f }, { "snareReverb", 0.3f },
            { "hatClosedCharacter", 0.0f }, { "hatClosedTune", 5 }, { "hatClosedLevel", -6 }, { "drive", 0.65f } },
          { { "x... .... ..x. ....", ".... .... X... ....", ".... .... X... ....", none, none, "..x. ..x. ..x. ..x.",
              none, none },
            { "x... ..x. ..x. ....", ".... .... X... ...x", ".... .... X... ....", none, none,
              "..x. ..x. ..x. .xxx", none, none } } },

        // Off the beaten track: triplets, glitches and machines.
        { "Triolen-Shuffle", "Experimentell",
          { { "master", 2 }, { "rate", triplets }, { "length", 12 }, { "kickDecay", 400 }, { "tomLowTune", 3 }, { "tomHighTune", 7 },
            { "hatClosedLevel", -3 }, { "hatOpenLevel", -4 } },
          { { "x..... x.....", "...x.. ...x..", none, none, none, "x.xx.x x.xx.x", none, none },
            { "x..... x...x.", "...x.. ...x.x", none, ".....x ......", "....x. ......", "x.xx.x x.xx..",
              "...... .....x", none } } },
        { "Glitch-Perkussion", "Experimentell",
          { { "master", -3 }, { "rate", thirtySeconds }, { "length", 32 }, { "kickDecay", 200 }, { "kickTone", 0.8f },
            { "snareDecay", 90 }, { "snareTone", 0.9f }, { "clapCharacter", 0.0f }, { "tomLowTune", 12 },
            { "tomLowDecay", 90 }, { "tomLowTone", 1.0f }, { "tomLowDelay", 0.5f }, { "tomHighTune", 19 },
            { "tomHighDecay", 60 }, { "tomHighTone", 1.0f }, { "tomHighDelay", 0.5f }, { "hatClosedDecay", 15 },
            { "fxDelayDivision", delaySixteenth }, { "fxDelayFeedback", 0.55f } },
          { { "x....... x.x..... ....x... ........", "........ ........ x....... ...x.x.x", "....xxxx ........ ........ ........",
              "......x. ........ ......x. ........", "........ ...x.... ........ .x...x..",
              "x.x.x.x. xxxxxxxx x.x.x.x. x.x.xxxx", none, none } } },
        { "Metall-Werkstatt", "Experimentell",
          { { "master", -2 }, { "kickDecay", 350 }, { "kickCharacter", 0.7f }, { "tomLowTone", 1.0f }, { "tomLowDecay", 300 },
            { "tomHighTone", 1.0f }, { "tomHighTune", 7 }, { "tomHighDecay", 250 }, { "hatClosedCharacter", 0.0f },
            { "hatOpenCharacter", 0.0f }, { "hatOpenTune", -5 }, { "cymbalCharacter", 0.0f }, { "cymbalTune", 7 },
            { "cymbalDecay", 900 }, { "cymbalLevel", -6 }, { "fxDelayDivision", delayQuarter } },
          { { "x... ..x. x... ....", none, ".... x... .... x...", "...x .... .... .x..", ".... ..x. .x.. ....",
              "x.x. xx.x x.x. xx.x", "..x. .... ..x. ....", ".... .... x... ...." } } },
    };
    return kits;
}
} // namespace tonwerkgroove
